---
title: "Course materials"
---

## Textbooks

You are not required to purchase a textbook for this class. However, if you wish to follow along with one, these are good options:

-   `[DS]` *Probability and Statistics* by Morris DeGroot and Mark Schervish;
-   `[Wass]` *All of Statistics* by Larry Wasserman.

In the **PREPARE** column of the [course schedule](https://anyakatsevich.github.io/sta332-f26/), I will indicate which parts of `[DS]` or `[Wass]` correspond to the lectures. Notes will be posted in the **MATERIALS** column; I will do my best to post them before lecture, but no guarantees.

## Technology

Lecture will largely be a low tech affair: pencil and paper will suffice. In general, you will need access to a device with internet so that you can use the following:

-   [This course page](https://anyakatsevich.github.io/sta332-f26/) that you are on right now;
-   [Canvas](https://go.canvas.duke.edu/), through which you can access...
    -   [Gradescope](https://www.gradescope.com/courses/82894);
    -   [Ed Discussion](https://edstem.org/us/courses/103644/discussion);
-   [Zoom](https://duke.zoom.us/) (e.g. for remote office hours).

If access to technology becomes a concern for you during the semester, contact the instructor immediately to discuss options.
