---
title: "Course overview"
editor: 
  mode: source
---

## Description

This course provides an introduction to the mathematical foundation underlying statistical learning and inference. It introduces concepts and methods from the classical theory of statistics, with a focus on point estimation, interval estimation, and hypothesis testing, along with their adjacent topics and their application.  

**Brief overview of topics** Introduction to the problems of Statistical Inference. Definition of random sample, statistical model and likelihood. Definition and properties of estimators and sufficient and complete statistics. Point estimation: comparing estimators in decision theoretic framework (loss functions, risk, mean squared error) and optimality results (Uniform Minimum Variance Estimators, Fisher's information, Cramer's Rao Lower bound). Hypothesis testing: comparing testing procedures and constructing optimal tests within the Neyman-Pearson framework. Tests based on the likelihood ratio. Confidence intervals: construction based on inverting tests. Asymptotic considerations: consistent and asymptotically efficient estimators. Likelihood-based asymptotic tests and confidence intervals.

**Prerequisites:** (Statistical Science 240L, 230, or 231) and (Mathematics 202, 212, 219, or 222). Recommended prerequisite: Statistical Science 210, 360, and (Mathematics 221, 218, or 216). Specifically, students should be fluent in calculus (differentiation, integration, etc.), and probability (discrete and continuous random variables, joint, marginal and conditional distributions, etc). Familiarity with basic estimation concepts such as the maximum likelihood principle and Bayes rule is helpful.


## Meetings

| Meeting  | Location                       | Time                   | 
|----------|--------------------------------|------------------------|
| Lecture | Gross Hall 103                   | TueThu 3:05 PM - 4:20 PM |
